{
 "title": "Consul Service_To_Service Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "source_service",
    "query": {
     "query": "label_values(consul_source_service)"
    }
   },
   {
    "name": "destination_service",
    "query": {
     "query": "label_values(consul_destination_service)"
    }
   },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "searchable_pattern", "label": "Search (case insensitive)" },
   {
    "name": "request_id",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Outbound Traffic Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Upstream Traffic: $source_service -> $destination_service",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "sum(irate(envoy_cluster_upstream_rq_total{local_cluster=~\"$source_service\",\nconsul_destination_service=~\"$destination_service\"}[10m])) by ( local_cluster, consul_destination_service)"
      }
     ]
    },
    {
     "title": "Upstream Request Response Timeliness: $source_service ->  $destination_service",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_upstream_rq_time_bucket{local_cluster=~\"$source_service\",consul_destination_target!=\"\"}[10m])) by (le, consul_destination_target))",
       "legendFormat": "{{consul_destination_target}}"
      }
     ]
    },
    {
     "title": "Upstream Request Success Rate: $source_service ->  $destination_service",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 44 },
     "targets": [
      {
       "expr": "sum(irate(envoy_cluster_upstream_rq_xx{envoy_response_code_class!=\"5\",local_cluster=~\"$source_service\",\nconsul_destination_service=~\"$destination_service\"}[10m])) by (local_cluster, consul_destination_service) / sum(irate(envoy_cluster_upstream_rq_xx{local_cluster=~\"$source_service\",consul_destination_service=~\"$destination_service\"}[10m])) by (local_cluster,consul_destination_service)\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Inbound Traffic Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests Sent: $source_service ->  $destination_service",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum(irate(envoy_cluster_upstream_rq_total{consul_destination_datacenter=\"dc1\", local_cluster=~\"$source_service\",\nconsul_destination_service=~\"$destination_service\"}[10m])) by (consul_destination_service, local_cluster)\n"
      }
     ]
    },
    {
     "title": "Request Success Rate: $source_service ->  $destination_service",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "sum(irate(envoy_cluster_upstream_rq_xx{envoy_response_code_class!=\"5\", local_cluster=~\"$source_service\", consul_destination_service=~\"$destination_service\"}[10m])) by (local_cluster, consul_destination_service) / sum(irate(envoy_cluster_upstream_rq_xx{consul_destination_service=~\"$destination_service\"}[10m])) by (local_cluster , consul_destination_service)"
      }
     ]
    },
    {
     "title": "Response Success by Status Code: $source_service ->  $destination_service",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum(increase(envoy_http_downstream_rq_xx{local_cluster=~\"$source_service\", envoy_http_conn_manager_prefix=\"public_listener\"}[10m])) by (local_cluster, envoy_response_code_class)"
      }
     ]
    },
    {
     "title": "Request Duration: $source_service -> $destination_service",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_upstream_rq_time_bucket{consul_destination_datacenter=\"dc1\", consul_destination_service=~\"$destination_service\",local_cluster=~\"$source_service\"}[10m])) by (le, cluster, local_cluster, consul_destination_service))"
      }
     ]
    },
    {
     "title": "Response Success: $source_service ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "sum(increase(envoy_http_downstream_rq_total{local_cluster=~\"$source_service\", envoy_http_conn_manager_prefix=\"public_listener\"}[10m])) by (local_cluster)"
      }
     ]
    },
    {
     "title": "Request Response Rate: $source_service",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "sum(irate(envoy_http_downstream_rq_total{local_cluster=~\"$source_service\",envoy_http_conn_manager_prefix=\"public_listener\"}[10m])) by (local_cluster)"
      }
     ]
    }
   ]
  },
  {
   "title": "Raw Logs",
   "type": "logs",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\"$source_service\", container!~\"consul-dataplane|vault-agent\", request_id=~\"$request_id\"} |= `request_id` | json | line_format `{{.request_id}} - {{.service_name}} - {{.pod}} - {{.client_ip}} - {{.event}} - {{.message}}`"
    }
   ]
  }
 ]
}