apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent-role
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-agent
  labels:
    app: payments-agent
spec:
  selector:
    matchLabels:
      app: payments-agent
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "agent-role"

        # Set auth method to JWT
        vault.hashicorp.com/auth-type: "jwt"
        vault.hashicorp.com/auth-path: "auth/k8s_jwt"

        # The "path" parameter for the JWT auth method is passed via this annotation:
        vault.hashicorp.com/auth-config-path: "/var/run/secrets/kubernetes.io/serviceaccount/token"
        
        # The template to fetch the OIDC token and write it to disk
        vault.hashicorp.com/agent-inject-secret-actor-token: "identity/oidc/token/agent-role"
        vault.hashicorp.com/agent-inject-template-actor-token: |
          {{- with secret "identity/oidc/token/agent-role" -}}
          {{ .Data.token }}
          {{- end -}}
        vault.hashicorp.com/tls-skip-verify: "true"
      labels:
        app: payments-agent
    spec:
      serviceAccountName: agent-role
      containers:
        - name: payments-agent
          image: jweissig/app:0.0.1